/**
 * Legacy URL redirects for the v2 rebuild.
 *
 * Everything editorial (posts, recipes, reports, tags) moved to
 * https://labs.thefocus.ai — the maps below were built from the live
 * sitemaps of both sites, so every URL that existed on thefocus.ai
 * points at a live destination.
 *
 * The site deploys to GitHub Pages, so these become <meta refresh>
 * redirect pages generated by Astro at build time.
 */

const LABS = "https://labs.thefocus.ai";
const COURSES = "https://courses.thefocus.ai";

// /posts/<slug> → labs /dispatch/<slug>, same slug unless noted.
const postSlugs = [
  "2025-11-22-ai-engineering-summit-takeaways",
  "agent-habitat",
  "agentic-yolo-with-warp-cursor-and-claude",
  "ai-engineering-code-summit-2025",
  "ai-for-research-deepresearch-wins",
  "building-an-intelligent-organization",
  "claude-code-non-coding",
  "clipboards-are-eating-the-world",
  "data-flywheel-pattern",
  "dont-be-passive-aggressive",
  "exposing-services-with-mcp",
  "feature-development-on-the-go",
  "gemma-4-umwelten-showdown",
  "geo-affordance",
  "good-for-human-good-for-ai",
  "gpt5-and-gpt-oss",
  "gpt5",
  "how-i-classify-models",
  "image-gen-on-apple-silicon",
  "june-2025-coding-agents-report",
  "laddering-up-from-chatboxes-to-autonomy",
  "local-models-typescript",
  "local-providers-which-open-model",
  "making-hard-things-easier",
  "mcp-tool-eval-mercury-umwelten",
  "microsoft-build-2025",
  "moral-vibe-check",
  "neural-harness",
  "notebooklm-for-research",
  "same-weights-different-results",
  "single-file-swift-code",
  "slicing-a-design-from-figma",
  "sraffas-gesture",
  "technical-debt-and-the-roi-threshhold",
  "the-car-wash-test",
  "the-new-touch-interface",
  "thoughts-on-gemini",
  "tools-for-thinking",
  "using-structured-output",
  "you-are-absolutely-right",
];

// Posts whose slug changed (or whose home is elsewhere).
const postOverrides = {
  "how-i-use-ai-jan-2026": `${LABS}/dispatch/how-ai-january-2026/`,
  "how-i-code-may-2026": `${LABS}/dispatch/how-ai-may-2026/`,
  "weekend-coding-agent": `${COURSES}/build-ai-coding-agent/`,
  "recipe-book": `${LABS}/recipes/`,
  about: "/studio/",
};

// /recipes/<id> → labs /recipes/<id>, 1:1.
const recipeSlugs = [
  "add-memory-to-cursor",
  "content-finder",
  "context7-mcp",
  "dagger-and-container-use",
  "extracting-requirements",
  "geolocation-prompt",
  "git-commit-messages",
  "iterating-designs-with-chatgpt4o",
  "lift-and-shift",
  "llm-for-quick-prototyping",
  "load-and-save-your-prompts",
  "making-meta-data",
  "playwright-mcp",
  "product-ideation",
  "repomix-redux",
  "repomix",
  "smallest-coding-agent",
  "superwhisper",
  "talking-in-the-car",
  "understanding-a-codebase",
  "use-cursor-in-slack",
  "using-claude-to-write-midjourney-prompts",
];

// Old recipe journey/tech listing pages — no per-page equivalent on labs.
const recipeListingPages = [
  "agents",
  "beginner",
  "claude",
  "clients",
  "context",
  "gemini",
  "images",
  "mcp",
  "prompts",
  "slack",
  "typescript",
  "voice",
];

// Root-level tag pages generated by the old [...tag].astro route.
const rootTagPages = [
  "affordance",
  "agents",
  "architecture",
  "azure",
  "benchmarks",
  "coding",
  "compare",
  "conference",
  "engineering",
  "essay",
  "gemini",
  "gemma",
  "harness",
  "infrastructure",
  "labs",
  "local-ai",
  "local-models",
  "maturity",
  "meta",
  "models",
  "org-age",
  "philosophy",
  "process",
  "report",
  "research",
  "summit",
  "tutorial",
  "typescript",
  "usecase",
  "workflow",
];

// /case-study/<id> → the new /work/ pages.
const caseStudyMap = {
  "tezlab-ai": "/work/#tezlab",
  "perplexity-samsung": "/work/perplexity-samsung/",
  qbsync: "/work/steering-house/",
  "fountain-creek": "/work/",
  distill: "/work/",
  "upperhand-ai": "/work/",
  "ai-back-office": "/work/",
  "image-browser": "/work/",
  onboarding: "/work/",
};

const redirects = {
  // Old site sections → new pages
  "/about": "/studio/",
  "/case-studies": "/work/",
  "/habitat-os": "/habitats/",
  "/jobs": "/studio/",
  "/jobs/junior-fullstack-developer": "/studio/",
  "/capabilities": "/",
  "/ai-maturity": "/",
  "/vibe-check": "/",
  "/production-ai-readiness": "/",
  "/lead-magnet/production-ai-readiness": "/",
  "/offerings/customer-onboarding": "/",
  "/offerings/executive-reporting": "/",
  "/offerings/hiring-pipeline": "/",
  "/offerings/invoice-processing": "/",
  "/offerings/monthly-close": "/",
  "/draft": "/",
  "/drafts": "/",
  "/emails": "/",

  // Editorial indexes → labs
  "/blog": `${LABS}/dispatch/`,
  "/insights": `${LABS}/dispatch/`,
  "/learnings": `${LABS}/dispatch/`,
  "/posts": `${LABS}/dispatch/`,
  "/tools": `${LABS}/recipes/`,
  "/tools/browse": `${LABS}/recipes/`,
  "/recipes": `${LABS}/recipes/`,
  "/recipies": `${LABS}/recipes/`,
  "/tags": `${LABS}/dispatch/`,
  "/use-cases": LABS,
  "/use-cases/coding/literacy": LABS,
  "/use-cases/flux-images": LABS,
  "/use-cases/flux-images/prince": LABS,
  "/use-cases/flux-images/steps": LABS,
  "/use-cases/flux-images/styles": LABS,
  "/rss.xml": `${LABS}/rss.xml`,

  // Reports → labs (same slugs), subsites → their real homes
  "/reports": `${LABS}/reports/`,
  "/coding-agents": `${LABS}/reports/`,
  "/reports/car-wash-test": `${LABS}/reports/car-wash-test/`,
  "/reports/local-providers": `${LABS}/reports/local-providers/`,
  "/reports/mcp-tool-test": `${LABS}/reports/mcp-tool-test/`,
  "/reports/model-showdown": `${LABS}/reports/model-showdown/`,
  "/reports/aiecode-2025-11": `${LABS}/dispatch/2025-11-22-ai-engineering-summit-takeaways/`,
  "/reports/coding-agent": `${COURSES}/build-ai-coding-agent/`,
  "/recipes/reports/coding-agent": `${COURSES}/build-ai-coding-agent/`,
};

for (const slug of postSlugs) {
  redirects[`/posts/${slug}`] = `${LABS}/dispatch/${slug}/`;
}
for (const [slug, target] of Object.entries(postOverrides)) {
  redirects[`/posts/${slug}`] = target;
}
for (const slug of recipeSlugs) {
  redirects[`/recipes/${slug}`] = `${LABS}/recipes/${slug}/`;
}
for (const page of recipeListingPages) {
  redirects[`/recipes/${page}`] = `${LABS}/recipes/`;
}
for (const tag of rootTagPages) {
  redirects[`/${tag}`] = `${LABS}/dispatch/`;
  redirects[`/tags/${tag}`] = `${LABS}/dispatch/`;
}
for (const [id, target] of Object.entries(caseStudyMap)) {
  redirects[`/case-study/${id}`] = target;
}

export default redirects;
