#!/bin/bash
#MISE description="Summarize the post for LinkedIn"

bash mise/tasks/run_prompt "$1" "You will act as a witty educated writer who is writing a linkedin post.  Write a linkedin post that summarizes the themes written here with the idea of getting people to click"
