#!/bin/bash
#MISE description="Summarize the post for LinkedIn"

bash mise/tasks/run_prompt "$1" "write a linkedin post that summarizes the themes written here with the idea of getting people to click"
